### ISSUE TITLE
Note To The Reviewer

### ISSUE THREAD

**Issue by Rayan84** [Rayan84/Recipe-app#1]
**Recipe App**

There are two developers contributing to this project.
https://github.com/Rayan84/Recipe-app/projects/1

**Comment by Emmyn5600** [comment]
Hi @alexander16108  and @Rayan84 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there.

## Required Changes :recycle:

- [ ] Instead of including the link for the GitHub repo, You are supposed to submit this [link](https://github.com/Rayan84/Recipe-app/projects/1)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!:clap::clap::clap:

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Rayan84** [comment]
> Hi @alexander16108 and @Rayan84
> 
> Good job so far! I know you have worked hard on making this milestone But There are some issues that you still need to work on to go to the next project but you are almost there.
> 
> ## Required Changes 
> * [ ]  Instead of including the link for the GitHub repo, You are supposed to submit this [link](https://github.com/Rayan84/Recipe-app/projects/1)
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!clapclapclap
> 
> #### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> #### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hello Emmy
The submission page doesn't accept that link

**Comment by Rayan84** [comment]
![Screenshot from 2022-02-28 18-13-57](https://user-images.githubusercontent.com/65650520/156028293-e062a049-dac8-4ca1-8017-1740f159a8c4.png)

**Comment by Emmyn5600** [comment]
@Rayan84 it is not that I meant,  I was saying to change this link you included in the issues https://github.com/Rayan84/Recipe-app with the one I sent you.

**Comment by Rayan84** [comment]
Thank you Emmy
